### ISSUE TITLE
Extended Ascii Character Error

### ISSUE THREAD

**Issue by ChuckTSI** [beetbox/pyacoustid#29]
Linux: Errors thrown if filename contains extended ASCII
python aidmatch.py "Björk - Tondeleyo.mp3" 

Traceback (most recent call last):
  File "aidmatch.py", line 51, in <module>
    aidmatch(sys.argv[1])
  File "aidmatch.py", line 46, in aidmatch
    print('%s - %s' % (artist, title))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 2: ordinal not in range(128)

**Comment by sampsyo** [comment]
Thanks! A couple of notes you might find interesting:

- This was a problem with the demo script's print statement, not the library itself, so you're good to go already if you just want to use the Python interface.
- This happened because your system has an ASCII locale, which you probably don't want in general. I'd suggest updating your `LC_ALL` or `LANG` environment variables to a UTF-8 locale.
- I fixed this for Python 2; a fix for Python 3 is surprisingly hard.
